<!DOCTYPE html>
<html lang="en">
<head>
  <title>10 Last Bitcoin's hashes</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>

    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    .navbar-brand {
      padding-top: 7px;
      padding-left: 10px;
    }

    .body {
      padding-bottom: 70px;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 100%;}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f7931a;
      height: 1000px;
    }

    @media (max-width: 767px) {
        .navbar-brand {
            padding: 0;
        }

        .navbar-brand img {
            margin-top: 5px;
            margin-left: 5px;
        }
    }

.navbar-center  {
  position: absolute;
  width: 100%;
  left: 0;
  text-align: center;
  padding-top: 5px;
  margin: auto;
  color:white;
  font-size: 200%;
}

  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="bitcoin_logo.png" rel="Bitcoin logo">
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <span class="navbar-center">Bitcoin Hashes</span>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">

  <div class="row content">
    <div class="col-sm-2 sidenav">
    </div>

    <div class="col-sm-8 text-left">
      <table class="table table-hover" style="margin-top: 100px;">
        <thead>
          <tr>
            <th>Block</th>
            <th>Hash Hexa</th>
            <th>Hash Binaire</th>
          </tr>
        </thead>
        <tbody>

        <?php
          $res = include('index.php');

          for($i=0; $i < count($res[0]; ++$i)) {
            echo '<tr data-url="https://www.blockchain.info/fr/block/'.$res[0][$i]'/">';
              echo '<td>'.$i.'</td>';
              echo '<td>'.$res[0].[$i].'</td>';
              echo '<td>'.$res[1].[$i].'</td>';
            echo '</tr>'
          }
        ?>
      </tbody>
    </table>
  </div>

    <div class="col-sm-2 sidenav">
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container">
  </div>
</nav>

</body>
</html>
